require:
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - '**/bin/**/*'
    - '**/db/**/*'
    - '**/config/**/*'
    - '**/.bundle/**/*'
    - '**/vendor/bundle/**/*'
